Sahar:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  base_arm_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_arm_joint
    pid: {p: 0.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  main_arm_position_controller:
    type: effort_controllers/JointPositionController
    joint: main_arm_joint
    pid: {p: 0.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  back_shaft_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_shaft_joint
    pid: {p: 0.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  supporter_position_controller:
    type: effort_controllers/JointPositionController
    joint: supporter_joint
    pid: {p: 70000.0, i: 1000.00, d: 20000.0, i_clamp: 70000}
  loader_position_controller:
    type: effort_controllers/JointPositionController
    joint: loader_joint
    pid: {p: 5000.0, i: 6.00, d: 1000.0, i_clamp: 60}
  back_cylinder_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_cylinder_joint
    pid: {p: 0.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  brackets_position_controller:
    type: effort_controllers/JointPositionController
    joint: brackets_joint
    pid: {p: 1000.0, i: 10.0, d: 100.0, i_clamp: 150.0}
