#IEDSIM
IEDSIM_sub_CustomIED: 'OCU'
IEDSIM_sub_Location: 'LOC'

IEDSIM_pub_IEDLocation: '/IED/Location'

#LLC
LLC_sub_WPDVelocity: 'WPD'
LLC_sub_WSMVelocity: 'WSM'
LLC_sub_BladePositionCommand: 'WSM'
LLC_sub_Location: 'LOC'
LLC_sub_PerVelocity: 'LOC'
LLC_sub_ConnectedToPlatform: 'LLI'

LLC_pub_EffortsTh: '/LLC/EFFORTS/Throttle'
LLC_pub_EffortsSt: '/LLC/EFFORTS/Steering'
LLC_pub_EffortsJn: '/LLC/EFFORTS/Joints'

#LLI
LLI_sub_EffortsTh: 'LLC'
LLI_sub_EffortsSt: 'LLC'
LLI_sub_EffortsJn: 'LLC'

LLI_pub_ConnectedToPlatform: '/Sahar/link_with_platform'

#OCU
OCU_sub_IEDLocation: 'IEDSIM'
OCU_sub_MissionAcceptance: 'SMME'
OCU_sub_LocalPath: 'PP'
OCU_sub_BladePosition: 'PER'
OCU_sub_Map: 'PER'
OCU_sub_Location: 'LOC'
OCU_sub_PerVelocity: 'LOC'

OCU_pub_CustomIED: '/OCU/IED/Location'
OCU_pub_PositionUpdate: '/OCU/PositionUpdate'
OCU_pub_AssignNavTask: '/OCU/SMME/NavigationTask'
OCU_pub_AssignManTask: '/OCU/SMME/ManipulationTask'
OCU_pub_AssignMission: '/OCU/SMME/MissionPlan'

#PER
PER_sub_Location: 'LOC'
PER_sub_PerVelocity: 'LOC'
PER_sub_SensorINS: 'SENSORS'
PER_sub_SensorGPS: 'SENSORS'
PER_sub_SensorCamL: 'SENSORS'
PER_sub_SensorCamR: 'SENSORS'
PER_sub_SensorWire: 'SENSORS'
PER_sub_SensorSICK1: 'SENSORS'
PER_sub_SensorSICK2: 'SENSORS'
PER_sub_SensorIBEO: 'SENSORS'
PER_sub_SensorGpsSpeed: 'SENSORS'
PER_sub_EffortsTh: 'LLC'
PER_sub_EffortsSt: 'LLC'
PER_sub_EffortsJn: 'LLC'

PER_pub_GPS: '/PER/GPS'
PER_pub_INS: '/PER/INS'
PER_pub_BladePosition: '/PER/BladPosition'
PER_pub_Map: '/PER/Map'
PER_pub_MiniMap: '/PER/MiniMap'
PER_pub_VOOdometry: '/PER/VOOdometry'
PER_pub_PerGpsSpeed: '/PER/GPS/Speed'

#PP
PP_sub_GlobalPath: 'SMME'
PP_sub_BladePosition: 'PER'
PP_sub_Map: 'PER'
PP_sub_Location: 'LOC'

PP_pub_LocalPath: '/PP/Path'

#SHIFFON2ROS
SHIFFON2ROS_pub_GPS: '/SENSORS/GPS'
SHIFFON2ROS_pub_INS: '/SENSORS/INS'
SHIFFON2ROS_pub_GpsSpeed: '/SENSORS/GPS/Speed'

#SMME
SMME_sub_AssignNavTask: 'OCU'
SMME_sub_AssignManTask: 'OCU'
SMME_sub_AssignMission: 'OCU'
SMME_sub_BladePosition: 'PER'
SMME_sub_Location: 'LOC'

SMME_pub_GlobalPath: '/SMME/GlobalPath'
SMME_pub_WorkSeqData: '/SMME/WSM/Task'
SMME_pub_MissionAcceptance: '/SMME/OCU/MissionAcceptance'

#SSM
SSM_sub_BladePosition: 'PER'
SSM_sub_Location: 'LOC'
SSM_sub_PerVelocity: 'LOC'


#WPD
WPD_sub_LocalPath: 'PP'
WPD_sub_MiniMap: 'PER'
WPD_sub_Location: 'LOC'

WPD_pub_WPDVelocity: '/WPD/Speed'

#WSM
WSM_sub_WorkSeqData: 'SMME'
WSM_sub_BladePosition: 'PER'
WSM_sub_MiniMap: 'PER'

WSM_pub_WSMVelocity: '/WSM/Speed'
WSM_pub_BladePositionCommand: '/WSM/BladePosition'

#LOC
LOC_sub_PositionUpdate: 'OCU'
LOC_sub_GPS: 'PER'
LOC_sub_INS: 'PER'
LOC_sub_VOOdometry: 'PER'
LOC_sub_PerGpsSpeed: 'PER'

LOC_pub_Location: '/LOC/Pose'
LOC_pub_PerVelocity: '/LOC/Velocity'

#SENSORS

SENSORS_pub_SensorINS: '/SENSORS/INS'
SENSORS_pub_SensorGPS: '/SENSORS/GPS'
SENSORS_pub_SensorCamL: '/SENSORS/CAM/L'
SENSORS_pub_SensorCamR: '/SENSORS/CAM/R'
SENSORS_pub_SensorWire: '/SENSORS/WIRE'
SENSORS_pub_SensorSICK1: '/SENSORS/SICK/1'
SENSORS_pub_SensorSICK2: '/SENSORS/SICK/2'
SENSORS_pub_SensorIBEO: '/SENSORS/IBEO/1'
SENSORS_pub_SensorGpsSpeed: '/SENSORS/GPS/Speed'

#PLATFORM
PLATFORM_sub_EffortsTh: 'LLC'
PLATFORM_sub_EffortsSt: 'LLC'
PLATFORM_sub_EffortsJn: 'LLC'

